---
- name: Install desktop environment
  hosts: all
  gather_facts: no

  vars:
    cask_packages:
      - brave-browser
      - discord
      - docker
      - iterm2

  tasks:
    - name: Install Homebrew Cask packages
      homebrew_cask: name={{ item }} state=latest
      with_items: "{{ cask_packages }}"
