---
- name: Install terminal environment
  hosts: all
  gather_facts: no

  vars:
    packages:
      - git
      - htop
      - jq
      - fzf
      - lsd
      - pyenv
      - pyenv-virtualenv
      - rg
      - shellcheck
      - wget
      - yarn
      - zlib
      - zsh
      - zsh-completions

    cask_packages:
      - emacs

  tasks:
    - name: Install Homebrew packages
      homebrew: name={{ packages }} state=latest
      tags:
        - homebrew
        - homebrew_only

    - name: Install Homebrew Cask packages
      homebrew_cask: name={{ cask_packages }} state=installed
      tags:
        - homebrew
        - homebrew_cask
